EXPECTED_COLS = [
  "consecutive","cod_eve","fec_not","semana","ano","cod_pre","cod_sub","edad","uni_med",
  "nacionalidad","nombre_nacionalidad","sexo","cod_pais_o","cod_dpto_o","cod_mun_o","area",
  "ocupacion","tip_ss","cod_ase","per_etn","gru_pob","nom_grupo","estrato","gp_discapa",
  "gp_desplaz","gp_migrant","gp_carcela","gp_gestan","sem_ges","gp_indigen","gp_pobicfb",
  "gp_mad_com","gp_desmovi","gp_psiquia","gp_vic_vio","gp_otros","fuente","cod_pais_r",
  "cod_dpto_r","cod_mun_r","cod_dpto_n","cod_mun_n","fec_con","ini_sin","tip_cas","pac_hos",
  "fec_hos","con_fin","fec_def","ajuste","fecha_nto","cer_def","cbmte","fec_arc_xl","fec_aju",
  "fm_fuerza","fm_unidad","fm_grado","confirmados","consecutive_origen","va_sispro",
  "estado_final_de_caso","nom_est_f_caso","nom_upgd","pais_ocurrencia","nombre_evento",
  "departamento_ocurrencia","municipio_ocurrencia","pais_residencia","departamento_residencia",
  "municipio_residencia","departamento_notificacion","municipio_notificacion"
]

DATE_COLS = {
    "fec_not","fec_con","ini_sin","fec_hos","fec_def",
    "fecha_nto","fec_arc_xl","fec_aju"
}
BOOLEAN_COLS = {"ajuste", "confirmados", "va_sispro"}

# Mapeo de encabezados (según tu archivo real)
ALIASES = {
    "CONSECUTIVE": "consecutive",
    "COD_EVE": "cod_eve",
    "FEC_NOT": "fec_not",
    "SEMANA": "semana",
    "ANO": "ano",
    "COD_PRE": "cod_pre",
    "COD_SUB": "cod_sub",
    "EDAD": "edad",
    "UNI_MED": "uni_med",
    "nacionalidad": "nacionalidad",
    "nombre_nacionalidad": "nombre_nacionalidad",
    "SEXO": "sexo",
    "COD_PAIS_O": "cod_pais_o",
    "COD_DPTO_O": "cod_dpto_o",
    "COD_MUN_O": "cod_mun_o",
    "AREA": "area",
    "OCUPACION": "ocupacion",
    "TIP_SS": "tip_ss",
    "COD_ASE": "cod_ase",
    "PER_ETN": "per_etn",
    "GRU_POB": "gru_pob",
    "nom_grupo": "nom_grupo",
    "estrato": "estrato",
    "GP_DISCAPA": "gp_discapa",
    "GP_DESPLAZ": "gp_desplaz",
    "GP_MIGRANT": "gp_migrant",
    "GP_CARCELA": "gp_carcela",
    "GP_GESTAN": "gp_gestan",
    "sem_ges": "sem_ges",
    "GP_INDIGEN": "gp_indigen",
    "GP_POBICFB": "gp_pobicfb",
    "GP_MAD_COM": "gp_mad_com",
    "GP_DESMOVI": "gp_desmovi",
    "GP_PSIQUIA": "gp_psiquia",
    "GP_VIC_VIO": "gp_vic_vio",
    "GP_OTROS": "gp_otros",
    "fuente": "fuente",
    "COD_PAIS_R": "cod_pais_r",
    "COD_DPTO_R": "cod_dpto_r",
    "COD_MUN_R": "cod_mun_r",
    "COD_DPTO_N": "cod_dpto_n",
    "COD_MUN_N": "cod_mun_n",
    "FEC_CON": "fec_con",
    "INI_SIN": "ini_sin",
    "TIP_CAS": "tip_cas",
    "PAC_HOS": "pac_hos",
    "FEC_HOS": "fec_hos",
    "CON_FIN": "con_fin",
    "FEC_DEF": "fec_def",
    "AJUSTE": "ajuste",
    "FECHA_NTO": "fecha_nto",
    "CER_DEF": "cer_def",
    "CBMTE": "cbmte",
    "FEC_ARC_XL": "fec_arc_xl",
    "FEC_AJU": "fec_aju",
    "FM_FUERZA": "fm_fuerza",
    "FM_UNIDAD": "fm_unidad",
    "FM_GRADO": "fm_grado",
    "confirmados": "confirmados",
    "consecutive_origen": "consecutive_origen",
    "va_sispro": "va_sispro",
    "Estado_final_de_caso": "estado_final_de_caso",
    "nom_est_f_caso": "nom_est_f_caso",
    "Nom_upgd": "nom_upgd",
    "Pais_ocurrencia": "pais_ocurrencia",
    "Nombre_evento": "nombre_evento",
    "Departamento_ocurrencia": "departamento_ocurrencia",
    "Municipio_ocurrencia": "municipio_ocurrencia",
    "Pais_residencia": "pais_residencia",
    "Departamento_residencia": "departamento_residencia",
    "Municipio_residencia": "municipio_residencia",
    "Departamento_Notificacion": "departamento_notificacion",
    "Municipio_notificacion": "municipio_notificacion"
}

TXT = ["sexo","tip_ss","cod_ase","cer_def","nom_est_f_caso","nom_upgd",
        "pais_ocurrencia","nombre_evento","departamento_ocurrencia","municipio_ocurrencia",
        "departamento_residencia","municipio_residencia","departamento_notificacion",
        "municipio_notificacion"]

COLUMNS = [
    "CONSECUTIVE","COD_EVE","FEC_NOT","SEMANA","ANO","COD_PRE","COD_SUB",
    "EDAD","UNI_MED","nacionalidad","nombre_nacionalidad","SEXO","COD_PAIS_O",
    "COD_DPTO_O","COD_MUN_O","AREA","OCUPACION","TIP_SS","COD_ASE","PER_ETN",
    "GRU_POB","nom_grupo","estrato","GP_DISCAPA","GP_DESPLAZ","GP_MIGRANT",
    "GP_CARCELA","GP_GESTAN","sem_ges","GP_INDIGEN","GP_POBICFB","GP_MAD_COM",
    "GP_DESMOVI","GP_PSIQUIA","GP_VIC_VIO","GP_OTROS","fuente","COD_PAIS_R",
    "COD_DPTO_R","COD_MUN_R","COD_DPTO_N","COD_MUN_N","FEC_CON","INI_SIN",
    "TIP_CAS","PAC_HOS","FEC_HOS","CON_FIN","FEC_DEF","AJUSTE","FECHA_NTO",
    "CER_DEF","CBMTE","FEC_ARC_XL","FEC_AJU","FM_FUERZA","FM_UNIDAD",
    "FM_GRADO","confirmados","consecutive_origen","va_sispro",
    "Estado_final_de_caso","nom_est_f_caso","Nom_upgd","Pais_ocurrencia",
    "Nombre_evento","Departamento_ocurrencia","Municipio_ocurrencia",
    "Pais_residencia","Departamento_residencia","Municipio_residencia",
    "Departamento_Notificacion","Municipio_notificacion"
]